[23기 최민] Add: 장바구니 수량 변경 기능 추가
wecode-bootcamp-korea/23-1st-RushOur-backend pull request #11
Opened 2021-08-10 07:48 UTC by Min-Ch

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 장바구니 수량 변경 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- patch를 이용하여 수량변경 가능

<img width="1005" alt="스크린샷 2021-08-10 오후 4 48 15" src="https://user-images.githubusercontent.com/84912594/128828979-d2a057ff-ac09-4323-a8d9-a8d679864df4.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 10:58 UTC, Kang-kyunghun requested changes

2021-08-11 10:58 UTC, Kang-kyunghun commented on carts/views.py
> +            if not Cart.objects.filter(id = cart_id).exists():
```suggestion
            if not Cart.objects.filter(id = cart_id, user = request.user).exists():
```
이런식으로 user와 같이 조건을 걸어서 가져 오면 아래의 조건문을 없애고 가독성을 높일 수 있습니다.

2021-08-11 10:58 UTC, Kang-kyunghun commented on carts/views.py
> +            user = request.user
```suggestion
          
```

2021-08-11 10:58 UTC, Kang-kyunghun commented on carts/views.py
> +            item = Cart.objects.get(id = cart_id)
```suggestion
            item = Cart.objects.get(id = cart_id, user = request.user)
```

2021-08-11 10:58 UTC, Kang-kyunghun commented on carts/views.py
> +                return JsonResponse({"message":"NOT_AUTH_USER"}, status=403)
```suggestion
            
```

2021-08-11 10:59 UTC, Kang-kyunghun commented
제가 일단 delete method만 봤습니다. delete method에 대한 리뷰 참고해서 patch에도 적용해 보세요.

2021-08-12 00:54 UTC, Kang-kyunghun requested changes

2021-08-12 00:54 UTC, Kang-kyunghun commented on carts/views.py
> +            item.quantity = int(data['quantity'])
```suggestion
            item          = Cart.objects.get(id = cart_id, user = request.user)
            item.quantity = int(data['quantity'])
```
= 기준으로 정렬해 주세요.

2021-08-12 00:54 UTC, Kang-kyunghun commented on carts/views.py
> +                "QUANTITY" : item.quantity}, status = 201)
```suggestion
            return JsonResponse({
                "message"  : "SUCCESS", 
                "QUANTITY" : item.quantity}, status = 200)
```
200이 조금 더 절절한 코드 같습니다.

2021-08-12 04:50 UTC, S2-J1NG commented
LGTM✨

2021-08-12 04:50 UTC, merged