[23기 최민] Add: 장바구니 옵션별 생성 기능 추가
wecode-bootcamp-korea/23-1st-RushOur-backend pull request #12
Opened 2021-08-11 06:11 UTC by Min-Ch

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 장바구니 옵션별 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

<img width="1032" alt="스크린샷 2021-08-11 오후 3 11 24" src="https://user-images.githubusercontent.com/84912594/128978432-6e3f0225-3c63-4eeb-a219-f52cac9da287.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 10:56 UTC, Kang-kyunghun requested changes

2021-08-11 10:56 UTC, Kang-kyunghun commented on carts/views.py
> +            return JsonResponse({"MESSAGE":"EMPTY_CART"}, status=200)
cart가 없으면 그냥 빈 list로 반환 되게 하시면 됩니다.

2021-08-11 10:56 UTC, Kang-kyunghun commented on carts/views.py
> +            shipping_price = 0
```suggestion
        SHIPPING_PRICE = 20000
        
        if total_price['total_price'] >= SHIPPING_PRICE :
            shipping_price = 0
```
일정 금액이 넘었을 때 무료 배송을 하는 것 같은데, 일정 금액이라는 부분은 기획에 따라 바뀔 수 있고, 여러 곳에서 사용할 수도 있으므로 상수화를 해주시면 좋을 것 같습니다. 그리고 기준 금액과 배송료를 구분해서 사용하시면 좋을 것 같아요.

2021-08-12 00:59 UTC, Kang-kyunghun requested changes

2021-08-12 00:59 UTC, Kang-kyunghun commented on carts/views.py
> +        total_price = Cart.objects.filter(user=user).aggregate(total=Sum(F('option__price')*F('quantity')))['total'] or 0
or 을 사용한 이유가 있나요? 이러면 결과가 boolean으로 나올 것 같아서요

2021-08-12 00:59 UTC, Kang-kyunghun commented on carts/views.py
> +        shipping_price = 0 if total_price > free_shipping or not total_price else 2500
상수화에 대해 다시 한 번 생각해 보세요. 
이해가 안 되면 라운지에서 순태님이나 수진님께 질문 부탁드리겠습니다.

2021-08-12 02:29 UTC, Min-Ch commented on carts/views.py
> +        total_price = Cart.objects.filter(user=user).aggregate(total=Sum(F('option__price')*F('quantity')))['total'] or 0
장바구니가 없으면 aggregate의 값이 None이 되어서, 

total_price에 None이면 0이 지정되게 하였습니다

2021-08-12 05:12 UTC, S2-J1NG commented on carts/views.py
> +        total_price = Cart.objects.filter(user=user).aggregate(total=Sum(F('option__price')*F('quantity')))['total'] or 0
`None` 일 경우에 대한 에러 처리 잘 하셨습니다! django의 `Coalesce`으로 처리 할 수도 있습니다.
<a href = "https://docs.djangoproject.com/en/3.2/ref/models/database-functions/">Coalesce</a> 내용 참고해서 적용해보세요!

2021-08-12 05:12 UTC, S2-J1NG commented on carts/views.py
> +        FREE_SHIPPING  = 20000
상수는 제일 위에 위치하게 됩니다. 
글로벌로 사용되는 상수라면 `from - import`  구문 밑에 위치하게 되며, 특정 클래스나 함수(특정 
 범위)에서만 사용된다면, 클래스나 함수 바로 밑에 위치하게 됩니다! 

```
def get(self, request):
       FREE_SHIPPING = 2000
```

2021-08-12 05:21 UTC, S2-J1NG commented
`aggregate`  반환 값으로 None 일 경우, 처리 하는 방법 추가로 확인하고 적용해주세요~!
코멘트 남겨 드렸습니다!

2021-08-12 07:05 UTC, S2-J1NG commented on carts/views.py
> +FREE_SHIPPING  = 20000
`def get(self, request): ` 함수에서만 FREE_SHIPPING 상수 사용되기 때문에 아래와 같이 수정해주세요!
```
def get(self, request):
     FREE_SHIPPING = 2000
     user = request.user
```

2021-08-12 07:07 UTC, Min-Ch commented on carts/views.py
> +FREE_SHIPPING  = 20000
수정하였습니다!

2021-08-12 07:23 UTC, S2-J1NG commented
LGTM 👍

2021-08-12 07:23 UTC, merged