[23기 최민] Add: 상품디테일페이지 기능 구현
wecode-bootcamp-korea/23-1st-RushOur-backend pull request #6
Opened 2021-08-06 12:09 UTC by Min-Ch

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 상품디테일페이지 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
<img width="1013" alt="스크린샷 2021-08-06 오후 9 06 45" src="https://user-images.githubusercontent.com/84912594/128508179-da803626-2e45-48df-80f7-80d098dca055.png">

![스크린샷 2021-08-06 오후 9 04 42](https://user-images.githubusercontent.com/84912594/128508232-878c432a-12e2-4636-9286-ce11c03477f0.png)
![스크린샷 2021-08-06 오후 9 04 48](https://user-images.githubusercontent.com/84912594/128508238-91849786-1f1a-4d07-9ed8-e4846755d9e1.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-09 01:33 UTC, Kang-kyunghun requested changes

2021-08-09 01:33 UTC, Kang-kyunghun commented on products/urls.py
> +    path('/detail/<int:product_id>', ProductDetailView.as_view()),
```suggestion
    path('/<int:product_id>', ProductDetailView.as_view()),
```

2021-08-09 01:33 UTC, Kang-kyunghun commented on products/views.py
> +class ProductDetailView(View):
```suggestion
class ProductView(View):
```

2021-08-09 01:33 UTC, Kang-kyunghun commented on products/views.py
> +            'subcategories': [subcategory.name for subcategory in subcategories],
카테고리와 서브카테고리를 다시 전부 주는 이유가 무엇인가요? 코멘트로 남겨주세요.

2021-08-09 01:33 UTC, Kang-kyunghun commented on products/views.py
> +            'detail_img'   : ProductDetailImage.objects.get(product=product).image_url
product로부터 이미지 가져와 주세요.

2021-08-09 01:33 UTC, Kang-kyunghun commented on products/views.py
> +        return JsonResponse({"detail_page":detail_page}, status=200)
```suggestion
        return JsonResponse({"result" : product}, status=200)
```
or
```suggestion
        return JsonResponse({"data" : product}, status=200)
```
결과에 대해서는 page가 아닌 해당 데이터가 무엇을 의미하는지가 중요합니다. 해당 데이터가 상세페이지에서만 쓰이는 것이 아닐수 있기 때문입니다.

2021-08-09 06:01 UTC, Min-Ch commented on products/views.py
> +class ProductDetailView(View):
경훈님 이미 ProductsView라는 class가 있어서 좀더 구분하기 쉽게 Detail을 추가하였는데 이렇게 수정해도 될까요?

2021-08-09 06:02 UTC, Min-Ch commented on products/views.py
> +            'subcategories': [subcategory.name for subcategory in subcategories],
이부분은 삭제하기로 하였습니다!

2021-08-10 01:45 UTC, Kang-kyunghun requested changes
해당 수정 사항만 수정되면 merge 하겠습니다.

2021-08-10 01:45 UTC, Kang-kyunghun commented on products/views.py
> +        product_data = {
```suggestion
        product      = Product.objects.get(id=product_id)
        product_data = {
```
사소한 것이지만 항상 확인해 주세요.

2021-08-10 01:45 UTC, Kang-kyunghun commented on products/views.py
> +            'tags'         : [tag.name for tag in product.tags.all()],
```suggestion
            'options'      : [{
                'size'  : option.size,
                'price' : option.price
             } for option in product.option_set.all()],
            'tags'         : [tag.name for tag in product.tags.all()],
```
다음과 같이 수정하는 것이 가독성 측면에서 더 좋을 것 같습니다.

2021-08-10 03:00 UTC, Min-Ch commented
경훈님 질문이 있어서 코멘트 남깁니다.

![스크린샷 2021-08-10 오전 11 53 26](https://user-images.githubusercontent.com/84912594/128801159-e8c58811-aea3-4fe3-82e8-e168a6f4fde2.png)

러쉬 홈페이지를 보시면 메인페이지에 '나만 알고싶은 향기' 처럼 제품 리스트를 보여주는 기능이 있습니다.

저희가 저 리스트에 8개만 쓰려고 하는데, 

원래는 리스트를 보내주면 프론트단에서 잘라서 사용을 하는 방법으로 되지 않을까 하는 생각이 있었습니다.

하지만 프론트에서 처리가 가능은 하지만, 맞춰서 보내주는 것이 더 좋다고 하여서 

 저 리스트를 보내주는 새로운 View(8개만 잘라서 보내주는)를 작성을 해야하는지,

 아니면 기존에 보내주는 기능에 필터링만 추가하여 구현을 해야하는지 궁금합니다.

2021-08-10 04:31 UTC, Kang-kyunghun commented
django에서 쿼리셋을 가져올 때 원하는 개수만 가져올 수 있는 방법이 있습니다. 이 방법을 활용하여 페이지네이션이나 무한 스크롤도 구현합니다.
한 번 찾아보시면 좋을 것 같아요. 이 방법을 적용하면 프론트에서 원하는 개수도 함께 주면 거기에 맞춰서 데이터를 줄 수 있습니다.
(hint 쿼리셋은 list와 비슷한 성질을 가지고 있습니다.)

2021-08-10 04:43 UTC, merged